cutoff_len: 1024
dataset: final_train_data
dataset_dir: /home2/xjw/LLaMA-Factory/data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /home2/xjw/model/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/e1945c40cd546c78e41f1151f4db032b271faeaa
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/LLaMA3-8B-Chat/lora/train_2024-06-02-02-26-15
packing: false
per_device_train_batch_size: 24
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: llama3
warmup_steps: 0
